apiVersion: v1
kind: Namespace
metadata:
  name: redspace
---  
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"   
  name: webserver
  labels:
    app: webserver
spec:
  ports:
  - port: 80
    name: webserver
    targetPort: 80
  type: NodePort
  selector:
    app: webserver
--- 
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" 
  name: redldap
  labels:
    app: redldap
spec:
  clusterIP: 10.101.28.72
  ports:
  - name: ldapserver
    port: 839
    targetPort: 839
  - name: ldapserveradmin
    port: 8090
    targetPort: 8090    
  selector:
    app: redldap
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      run: webserver
  replicas: 1
  template:
    metadata:
      labels:
        run: webserver
    spec:  
      containers:
      - name: webserver
        image: paisleyswerve/redimages:apex1
        ports:
        - containerPort: 80
---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redldap
  labels:
    app: redldap
spec:
  selector:
    matchLabels:
      run: redldap
  replicas: 1
  template:
    metadata:
      labels:
        run: redldap
    spec:
      volumes:
      - name: ldapdata
        hostPath:
          path: /var/lib/ldap
      - name: ldapconfig   
        hostPath:
          path: /etc/ldap/slapd.d
      containers:
      - name: ldapserver
        image: paisleyswerve/redimages:redldap 
        ports:
        - containerPort: 389 
        volumeMounts:
        - name: ldapdata
          mountPath: /var/lib/ldap
        - name: ldapconfig
          mountPath: /etc/ldap/slapd.d
      - name: ldapserveradmin
        image: paisleyswerve/redimages:redladmin         
        ports:
        - containerPort: 8090
        
