---
apiVersion: v1
kind: Service
metadata:
  name: posty
  labels:
    app: posty
spec:
  ports:
    - port: 5432
  selector:
    app: posty
    ##tier: postgreSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posty
  labels:
    app: posty
spec:
  replicas: 1
  containers:
  - name: postgres
    image: postgres
    env:
      - name: POSTGRES_USER
        value: admin
      - name: POSTGRES_PASSWORD
        value: password
  - name: adminer
    image: adminer
    ports:
    - containerPort: 8080
 ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: posty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
        
        
      

