---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: posty
  labels:
    app: posty
spec:
  ports:
  - port: 5432
    name: posty
    nodePort: 31432
  type: NodePort
  selector: 
    app: posty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posty
  labels:
    app: posty
spec:
  selector:
    matchLabels:
      app: posty
  replicas: 1
  template:
    metadata:
      labels:
        app: posty
    spec: 
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password
      - name: adminer
        image: adminer
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: posty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
        
        
      

